package it.polimi.ingsw.network.messages;

import it.polimi.ingsw.client.View;
import it.polimi.ingsw.network.CVMessage;
import it.polimi.ingsw.network.Message;
import it.polimi.ingsw.util.MessageType;

/**
 * This message is sent from the server to the client after accepting its connection request
 */
public class NotifyPlayerIdMessage extends Message implements CVMessage {
    private final String playerId;

    /**
     * Constructor: build the message
     * @param playerId player ID generated by the server
     */
    public NotifyPlayerIdMessage(String playerId){
        super(MessageType.CV);
        this.playerId = playerId;
    }

    @Override
    public void execute(View view) {
        view.setPlayerId(playerId);
    }
}
